version: '3.3'

networks:
  web-app:

services:
  web:
    image: mredw/web-custom
    depends_on:
      - mysql
    networks:
      - web-app
    ports:
      - "80"
    volumes:
      - ./file-web:/var/www/html/
    container_name: web
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 10s
      timeout: 10s
      retries: 3
      
  proxy:
    image: mredw/proxy-custom
    ports:
      - '80:80'
    networks:
      - web-app
    healthcheck:
        test: ["CMD", "service", "nginx", "status"]
        interval: 20s
        timeout: 10s
        retries: 3
    container_name: proxy

  mysql:
    image: mredw/mysql-custom
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: dbkuasai
      MYSQL_USER: cilsykuasaiuser
      MYSQL_PASSWORD: cilsykuasaipassword
    volumes:
       - mysql-data:/var/lib/mysql
    ports:
       - "3306"
    networks:
       - web-app
    container_name: mysql   

  phpmyadmin:
    image: mredw/pma-custom
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: password
      PMA_PASSWORD: cilsykuasaipassword
    ports:
       - "80"
    networks:
      - web-app
    container_name: pma
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 10s
      timeout: 10s
      retries: 3
 

volumes:
  mysql-data:
