version: '3.3'

networks:
  web-app:

services:
  web:
    image: mredw/web:1.0.0
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mysql
    healthcheck:
        test: ["CMD", "curl", "-f", "http://www.web.local"]
        interval: 10s
        timeout: 10s
        retries: 3
    networks:
      - web-app
    ports:
      - "8080:80"
    volumes:
      - ./file-web:/var/www/html/
    container_name: web
      
  proxy:
    image: nginx:1.19 
    build:
      context: .
      dockerfile: nginx.Dockerfile
    ports:
      - '80:80'
    networks:
      - web-app
    healthcheck:
        test: ["CMD", "service", "nginx", "status"]
        interval: 10s
        timeout: 10s
        retries: 3
    container_name: proxy

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: dbkuasai
      MYSQL_USER: cilsykuasaiuser
      MYSQL_PASSWORD: cilsykuasaipassword
    volumes:
       - mysql-data:/var/lib/mysql
    ports:
       - "3306"
    networks:
       - web-app
    container_name: mysql   

  phpmyadmin:
    image: phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: password
      PMA_PASSWORD: cilsykuasaipassword
    ports:
       - 8081:80
    networks:
      - web-app
    container_name: pma
 

volumes:
  mysql-data:
